using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Phantom.CQRS.SourceGenerator;

/// <summary>
/// Incremental Source Generator that produces a compile-time, reflection-free dispatcher
/// for all ICommand, ICommand&lt;TResult&gt;, and IQuery&lt;TResult&gt; types found in the compilation.
/// </summary>
[Generator]
public class DispatcherGenerator : IIncrementalGenerator
{
    private const string CommandInterfaceFullName = "Phantom.CQRS.Commands.ICommand";
    private const string CommandOfTInterfaceFullName = "Phantom.CQRS.Commands.ICommand<TResult>";
    private const string QueryInterfaceFullName = "Phantom.CQRS.Queries.IQuery<TResult>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all types that could be commands or queries
        var typeInfos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateType(node),
                transform: static (ctx, _) => GetTypeSemanticInfo(ctx))
            .Where(static info => info is not null);

        var collectedTypes = typeInfos.Collect();

        context.RegisterSourceOutput(collectedTypes, static (spc, types) =>
        {
            GenerateDispatcher(spc, types!);
        });
    }

    private static bool IsCandidateType(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax;
    }

    private static TypeInfo? GetTypeSemanticInfo(GeneratorSyntaxContext context)
    {
        var typeDecl = (TypeDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;

        if (symbol is null || symbol.IsAbstract)
            return null;

        // Skip open generic types (e.g., MyGenericClass<T>)
        if (symbol.IsGenericType && symbol.TypeArguments.Any(t => t.TypeKind == TypeKind.TypeParameter))
            return null;

        var kind = CommandKind.None;
        ITypeSymbol? resultType = null;

        foreach (var iface in symbol.AllInterfaces)
        {
            var ifaceFullName = iface.ConstructedFrom?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "";

            if (ifaceFullName == "global::Phantom.CQRS.Commands.ICommand")
            {
                kind = CommandKind.Command;
            }
            else if (ifaceFullName.StartsWith("global::Phantom.CQRS.Commands.ICommand<"))
            {
                kind = CommandKind.CommandWithResult;
                resultType = iface.TypeArguments.FirstOrDefault();
            }
            else if (ifaceFullName.StartsWith("global::Phantom.CQRS.Queries.IQuery<"))
            {
                kind = CommandKind.Query;
                resultType = iface.TypeArguments.FirstOrDefault();
            }
        }

        if (kind == CommandKind.None)
            return null;

        return new TypeInfo(
            symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            kind,
            resultType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
    }

    private static void GenerateDispatcher(SourceProductionContext context, IReadOnlyList<TypeInfo> types)
    {
        if (types.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Phantom CQRS Source Generator - Generated Dispatcher");
        sb.AppendLine("// This file was auto-generated by Phantom.CQRS.SourceGenerator");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Phantom.CQRS.Commands;");
        sb.AppendLine("using Phantom.CQRS.Dispatchers;");
        sb.AppendLine("using Phantom.CQRS.Exceptions;");
        sb.AppendLine("using Phantom.CQRS.Pipelines;");
        sb.AppendLine("using Phantom.CQRS.Queries;");
        sb.AppendLine();
        sb.AppendLine("namespace Phantom.CQRS.Dispatchers;");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Compile-time generated dispatcher - zero reflection overhead.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class GeneratedDispatcher : IDispatcher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine("    public GeneratedDispatcher(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _serviceProvider = serviceProvider;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate SendAsync for ICommand (no result)
        GenerateSendAsyncCommand(sb, types);

        // Generate SendAsync for ICommand<TResult>
        GenerateSendAsyncCommandWithResult(sb, types);

        // Generate QueryAsync for IQuery<TResult>
        GenerateQueryAsync(sb, types);

        // Generate individual handler methods
        foreach (var type in types)
        {
            switch (type.Kind)
            {
                case CommandKind.Command:
                    GenerateCommandHandlerMethod(sb, type);
                    break;
                case CommandKind.CommandWithResult:
                    GenerateCommandWithResultHandlerMethod(sb, type);
                    break;
                case CommandKind.Query:
                    GenerateQueryHandlerMethod(sb, type);
                    break;
            }
        }

        sb.AppendLine("}");

        context.AddSource("GeneratedDispatcher.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateSendAsyncCommand(StringBuilder sb, IReadOnlyList<TypeInfo> types)
    {
        var commands = types.Where(t => t.Kind == CommandKind.Command).ToList();

        sb.AppendLine("    public async Task SendAsync<TCommand>(TCommand command, CancellationToken cancellationToken = default) where TCommand : ICommand");
        sb.AppendLine("    {");

        if (commands.Count > 0)
        {
            sb.AppendLine("        switch (command)");
            sb.AppendLine("        {");
            foreach (var cmd in commands)
            {
                sb.AppendLine($"            case {cmd.FullyQualifiedName} c{commands.IndexOf(cmd)}:");
                sb.AppendLine($"                await Handle_{SanitizeName(cmd.FullyQualifiedName)}(c{commands.IndexOf(cmd)}, cancellationToken);");
                sb.AppendLine("                return;");
            }
            sb.AppendLine("        }");
        }

        sb.AppendLine("        throw new HandlerNotFoundException(typeof(TCommand),");
        sb.AppendLine("            $\"No handler registered for command type '{typeof(TCommand).FullName}'.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateSendAsyncCommandWithResult(StringBuilder sb, IReadOnlyList<TypeInfo> types)
    {
        var commandsWithResult = types.Where(t => t.Kind == CommandKind.CommandWithResult).ToList();

        sb.AppendLine("    public async Task<TResult> SendAsync<TResult>(ICommand<TResult> command, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");

        if (commandsWithResult.Count > 0)
        {
            sb.AppendLine("        switch (command)");
            sb.AppendLine("        {");
            foreach (var cmd in commandsWithResult)
            {
                sb.AppendLine($"            case {cmd.FullyQualifiedName} c{commandsWithResult.IndexOf(cmd)}:");
                sb.AppendLine($"                var result{commandsWithResult.IndexOf(cmd)} = await Handle_{SanitizeName(cmd.FullyQualifiedName)}(c{commandsWithResult.IndexOf(cmd)}, cancellationToken);");
                sb.AppendLine($"                return (TResult)(object)result{commandsWithResult.IndexOf(cmd)};");
                sb.AppendLine("                // Unreachable - the type system ensures TResult matches");
                sb.AppendLine("                return default!;");
            }
            sb.AppendLine("        }");
        }

        sb.AppendLine("        throw new HandlerNotFoundException(command.GetType(),");
        sb.AppendLine("            $\"No handler registered for command type '{command.GetType().FullName}' with result type '{typeof(TResult).FullName}'.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateQueryAsync(StringBuilder sb, IReadOnlyList<TypeInfo> types)
    {
        var queries = types.Where(t => t.Kind == CommandKind.Query).ToList();

        sb.AppendLine("    public async Task<TResult> QueryAsync<TResult>(IQuery<TResult> query, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");

        if (queries.Count > 0)
        {
            sb.AppendLine("        switch (query)");
            sb.AppendLine("        {");
            foreach (var q in queries)
            {
                sb.AppendLine($"            case {q.FullyQualifiedName} c{queries.IndexOf(q)}:");
                sb.AppendLine($"                var qresult{queries.IndexOf(q)} = await Handle_{SanitizeName(q.FullyQualifiedName)}(c{queries.IndexOf(q)}, cancellationToken);");
                sb.AppendLine($"                return (TResult)(object)qresult{queries.IndexOf(q)};");
                sb.AppendLine("                // Unreachable - the type system ensures TResult matches");
                sb.AppendLine("                return default!;");
            }
            sb.AppendLine("        }");
        }

        sb.AppendLine("        throw new HandlerNotFoundException(query.GetType(),");
        sb.AppendLine("            $\"No handler registered for query type '{query.GetType().FullName}' with result type '{typeof(TResult).FullName}'.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateCommandHandlerMethod(StringBuilder sb, TypeInfo type)
    {
        var name = SanitizeName(type.FullyQualifiedName);
        sb.AppendLine($"    private async Task Handle_{name}({type.FullyQualifiedName} command, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var scope = _serviceProvider.CreateScope();");
        sb.AppendLine($"        var handler = scope.ServiceProvider.GetService<ICommandHandler<{type.FullyQualifiedName}>>()");
        sb.AppendLine($"            ?? throw new HandlerNotFoundException(typeof({type.FullyQualifiedName}),");
        sb.AppendLine($"                $\"No handler registered for command type '{{typeof({type.FullyQualifiedName}).FullName}}'.\");");
        sb.AppendLine();
        sb.AppendLine($"        var behaviors = scope.ServiceProvider.GetServices<IPipelineBehavior<{type.FullyQualifiedName}>>().Reverse().ToList();");
        sb.AppendLine();
        sb.AppendLine("        RequestHandlerDelegate handlerDelegate = () => handler.HandleAsync(command, cancellationToken);");
        sb.AppendLine("        foreach (var behavior in behaviors)");
        sb.AppendLine("        {");
        sb.AppendLine("            var current = handlerDelegate;");
        sb.AppendLine("            handlerDelegate = () => behavior.HandleAsync(command, current, cancellationToken);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        await handlerDelegate();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateCommandWithResultHandlerMethod(StringBuilder sb, TypeInfo type)
    {
        var name = SanitizeName(type.FullyQualifiedName);
        var resultType = type.ResultType ?? "object";
        sb.AppendLine($"    private async Task<{resultType}> Handle_{name}({type.FullyQualifiedName} command, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var scope = _serviceProvider.CreateScope();");
        sb.AppendLine($"        var handler = scope.ServiceProvider.GetService<ICommandHandler<{type.FullyQualifiedName}, {resultType}>>()");
        sb.AppendLine($"            ?? throw new HandlerNotFoundException(typeof({type.FullyQualifiedName}),");
        sb.AppendLine($"                $\"No handler registered for command type '{{typeof({type.FullyQualifiedName}).FullName}}'.\");");
        sb.AppendLine();
        sb.AppendLine($"        var behaviors = scope.ServiceProvider.GetServices<IPipelineBehavior<{type.FullyQualifiedName}>>().Reverse().ToList();");
        sb.AppendLine();
        sb.AppendLine($"        Func<Task<{resultType}>> currentDelegate = () => handler.HandleAsync(command, cancellationToken);");
        sb.AppendLine("        foreach (var behavior in behaviors)");
        sb.AppendLine("        {");
        sb.AppendLine("            var current = currentDelegate;");
        sb.AppendLine($"            currentDelegate = async () =>");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                var tcs = new TaskCompletionSource<{resultType}>();");
        sb.AppendLine($"                var next = new RequestHandlerDelegate(async () =>");
        sb.AppendLine($"                {{");
        sb.AppendLine($"                    var result = await current();");
        sb.AppendLine($"                    tcs.SetResult(result);");
        sb.AppendLine($"                }});");
        sb.AppendLine($"                await behavior.HandleAsync(command, next, cancellationToken);");
        sb.AppendLine($"                return await tcs.Task;");
        sb.AppendLine($"            }};");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return await currentDelegate();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateQueryHandlerMethod(StringBuilder sb, TypeInfo type)
    {
        var name = SanitizeName(type.FullyQualifiedName);
        var resultType = type.ResultType ?? "object";
        sb.AppendLine($"    private async Task<{resultType}> Handle_{name}({type.FullyQualifiedName} query, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var scope = _serviceProvider.CreateScope();");
        sb.AppendLine($"        var handler = scope.ServiceProvider.GetService<IQueryHandler<{type.FullyQualifiedName}, {resultType}>>()");
        sb.AppendLine($"            ?? throw new HandlerNotFoundException(typeof({type.FullyQualifiedName}),");
        sb.AppendLine($"                $\"No handler registered for query type '{{typeof({type.FullyQualifiedName}).FullName}}'.\");");
        sb.AppendLine();
        sb.AppendLine($"        var behaviors = scope.ServiceProvider.GetServices<IPipelineBehavior<{type.FullyQualifiedName}>>().Reverse().ToList();");
        sb.AppendLine();
        sb.AppendLine($"        Func<Task<{resultType}>> currentDelegate = () => handler.HandleAsync(query, cancellationToken);");
        sb.AppendLine("        foreach (var behavior in behaviors)");
        sb.AppendLine("        {");
        sb.AppendLine("            var current = currentDelegate;");
        sb.AppendLine($"            currentDelegate = async () =>");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                var tcs = new TaskCompletionSource<{resultType}>();");
        sb.AppendLine($"                var next = new RequestHandlerDelegate(async () =>");
        sb.AppendLine($"                {{");
        sb.AppendLine($"                    var result = await current();");
        sb.AppendLine($"                    tcs.SetResult(result);");
        sb.AppendLine($"                }});");
        sb.AppendLine($"                await behavior.HandleAsync(query, next, cancellationToken);");
        sb.AppendLine($"                return await tcs.Task;");
        sb.AppendLine($"            }};");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return await currentDelegate();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string SanitizeName(string fullyQualifiedName)
    {
        // Convert global::Namespace.TypeName to Namespace_TypeName
        var name = fullyQualifiedName.Replace("global::", "").Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(",", "_");
        // Remove duplicate underscores
        while (name.Contains("__"))
            name = name.Replace("__", "_");
        return name.TrimEnd('_');
    }

    private enum CommandKind
    {
        None,
        Command,
        CommandWithResult,
        Query
    }

    private sealed class TypeInfo
    {
        public string FullyQualifiedName { get; }
        public CommandKind Kind { get; }
        public string? ResultType { get; }

        public TypeInfo(string fullyQualifiedName, CommandKind kind, string? resultType)
        {
            FullyQualifiedName = fullyQualifiedName;
            Kind = kind;
            ResultType = resultType;
        }
    }
}
