namespace Phantom.AspNetCore.ProblemDetails;

/// <summary>
/// Represents an RFC 7807 Problem Detail response for the Phantom framework.
/// </summary>
public class PhantomProblemDetail
{
    /// <summary>
    /// A URI reference that identifies the problem type. When dereferenced, it should
    /// provide human-readable documentation for the problem type.
    /// </summary>
    public string? Type { get; set; }

    /// <summary>
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type. It should not change
    /// from occurrence to occurrence of the problem, except for purposes of localization.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string Detail { get; set; } = string.Empty;

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// Typically the request path that caused the error.
    /// </summary>
    public string? Instance { get; set; }

    /// <summary>
    /// The trace identifier for correlating this error with server-side logs.
    /// </summary>
    public string? TraceId { get; set; }

    /// <summary>
    /// Per-field validation errors, where the key is the field/property name and the
    /// value is an array of error messages for that field.
    /// </summary>
    public Dictionary<string, string[]>? Errors { get; set; }
}
